// 88. WRITE A C PROGRAM TO FIND THE SUM OF THE EVEN DIGITS AND THE SUM OF THE ODD DIGITS SEPARATELY IN A GIVEN NUMBER USING LOOPS AND IF-ELSE STATEMENTS?

#include <stdio.h>

int main() {
    // Your code here
    return 0;
}
